
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { AlertTriangle, Users, TrendingUp, MapPin, Calendar, Shield, Download } from "lucide-react";
import Dashboard from "@/components/Dashboard";
import GeographicView from "@/components/GeographicView";
import TrendAnalysis from "@/components/TrendAnalysis";
import ResourceAllocation from "@/components/ResourceAllocation";
import IncidentReporting from "@/components/IncidentReporting";
import PredictiveAnalytics from "@/components/PredictiveAnalytics";

const Index = () => {
  const handleDownloadReport = () => {
    // Create a comprehensive report
    const reportData = {
      title: "Kenya GBV Analytics Report",
      generatedDate: new Date().toLocaleDateString(),
      summary: {
        totalIncidents: 1247,
        resolvedCases: 1089,
        activeCases: 158,
        emergencyCalls: 89
      },
      counties: [
        { name: "Nairobi", incidents: 156, trend: "up" },
        { name: "Mombasa", incidents: 89, trend: "down" },
        { name: "Kisumu", incidents: 67, trend: "up" },
        { name: "Nakuru", incidents: 45, trend: "stable" }
      ],
      incidentTypes: [
        { type: "Domestic Violence", percentage: 45 },
        { type: "Sexual Violence", percentage: 25 },
        { type: "Emotional Abuse", percentage: 20 },
        { type: "Economic Abuse", percentage: 10 }
      ]
    };

    const reportContent = `
KENYA GBV INSIGHT HUB - ANALYTICS REPORT
Generated: ${reportData.generatedDate}

EXECUTIVE SUMMARY
================
Total Incidents (YTD): ${reportData.summary.totalIncidents}
Cases Resolved: ${reportData.summary.resolvedCases} (${((reportData.summary.resolvedCases/reportData.summary.totalIncidents)*100).toFixed(1)}%)
Active Cases: ${reportData.summary.activeCases}
Emergency Calls: ${reportData.summary.emergencyCalls}

HIGH-RISK COUNTIES
==================
${reportData.counties.map(county => `${county.name}: ${county.incidents} incidents (${county.trend})`).join('\n')}

INCIDENT DISTRIBUTION
====================
${reportData.incidentTypes.map(type => `${type.type}: ${type.percentage}%`).join('\n')}

RECOMMENDATIONS
===============
1. Increase counselor availability in high-risk areas
2. Deploy mobile support units during peak periods
3. Strengthen community awareness programs
4. Enhance emergency response capabilities

This report is generated by the Kenya GBV Insight Hub platform for policy makers, NGOs, and law enforcement agencies.
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Kenya-GBV-Report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen relative overflow-hidden font-roboto">
      {/* Background Design */}
      <div className="absolute inset-0 bg-gradient-to-br from-purple-100 via-blue-50 to-green-100">
        <div 
          className="absolute inset-0 opacity-20"
          style={{
            backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%239C92AC' fill-opacity='0.1'%3E%3Ccircle cx='30' cy='30' r='4'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`
          }}
        ></div>
        <div className="absolute top-20 left-10 w-32 h-32 bg-blue-200 rounded-full opacity-30 blur-xl"></div>
        <div className="absolute bottom-20 right-20 w-40 h-40 bg-purple-200 rounded-full opacity-30 blur-xl"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-60 h-60 bg-green-200 rounded-full opacity-20 blur-2xl"></div>
      </div>

      {/* Header */}
      <header className="relative bg-white/90 backdrop-blur-sm shadow-sm border-b">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Shield className="h-8 w-8 text-blue-600" />
              <div className="flex items-center space-x-4">
                <div>
                  <h1 className="text-2xl font-bold text-gray-900">Kenya GBV Insight Hub</h1>
                  <p className="text-sm text-gray-600">Analytics-Driven Violence Prevention Platform</p>
                </div>
                {/* Kenyan Girl Representation */}
                <div className="hidden md:flex items-center space-x-2 bg-gradient-to-r from-green-500 via-white to-red-500 p-2 rounded-lg">
                  <div className="w-8 h-8 bg-gradient-to-br from-amber-600 to-amber-800 rounded-full flex items-center justify-center">
                    <span className="text-white font-bold text-xs">KE</span>
                  </div>
                  <span className="text-sm font-medium text-gray-700">Empowering Kenyan Women</span>
                </div>
              </div>
            </div>
            <div className="flex items-center space-x-4">
              <Button 
                variant="outline" 
                size="sm"
                onClick={handleDownloadReport}
                className="flex items-center space-x-2"
              >
                <Download className="h-4 w-4" />
                <span>Download Report</span>
              </Button>
              <Button variant="outline" size="sm">
                <AlertTriangle className="h-4 w-4 mr-2" />
                Emergency Resources
              </Button>
              <Button size="sm">
                <Users className="h-4 w-4 mr-2" />
                Partner Network
              </Button>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="relative container mx-auto px-6 py-8">
        <div className="mb-8">
          <div className="flex items-center space-x-4 mb-4">
            <div className="w-16 h-16 bg-gradient-to-br from-green-600 via-black to-red-600 rounded-full flex items-center justify-center shadow-lg">
              <Shield className="h-8 w-8 text-white" />
            </div>
            <div>
              <h2 className="text-3xl font-bold text-gray-900 mb-2">
                Empowering Data-Driven Action Against Gender-Based Violence
              </h2>
              <p className="text-lg text-gray-600 max-w-3xl">
                Comprehensive analytics platform providing real-time insights, trend analysis, and predictive modeling 
                to support effective resource allocation and targeted interventions across Kenya.
              </p>
            </div>
          </div>
          
          {/* Kenyan Girl Empowerment Section */}
          <div className="bg-white/80 backdrop-blur-sm rounded-lg p-4 mb-6 border border-gray-200 shadow-sm">
            <div className="flex items-center space-x-3">
              <div className="w-12 h-12 bg-gradient-to-br from-pink-400 to-purple-500 rounded-full flex items-center justify-center">
                <span className="text-white font-bold">👩🏾</span>
              </div>
              <div>
                <h3 className="font-semibold text-gray-900">Dedicated to Kenyan Women and Girls</h3>
                <p className="text-sm text-gray-600">Every data point represents a life we can protect and empower through informed action.</p>
              </div>
            </div>
          </div>
        </div>

        <Tabs defaultValue="dashboard" className="space-y-6">
          <TabsList className="grid grid-cols-6 w-full max-w-4xl mx-auto">
            <TabsTrigger value="dashboard" className="flex items-center space-x-2">
              <TrendingUp className="h-4 w-4" />
              <span>Dashboard</span>
            </TabsTrigger>
            <TabsTrigger value="geographic" className="flex items-center space-x-2">
              <MapPin className="h-4 w-4" />
              <span>Geographic</span>
            </TabsTrigger>
            <TabsTrigger value="trends" className="flex items-center space-x-2">
              <Calendar className="h-4 w-4" />
              <span>Trends</span>
            </TabsTrigger>
            <TabsTrigger value="resources" className="flex items-center space-x-2">
              <Users className="h-4 w-4" />
              <span>Resources</span>
            </TabsTrigger>
            <TabsTrigger value="reporting" className="flex items-center space-x-2">
              <AlertTriangle className="h-4 w-4" />
              <span>Report</span>
            </TabsTrigger>
            <TabsTrigger value="predictive" className="flex items-center space-x-2">
              <TrendingUp className="h-4 w-4" />
              <span>Predictive</span>
            </TabsTrigger>
          </TabsList>

          <TabsContent value="dashboard">
            <Dashboard />
          </TabsContent>

          <TabsContent value="geographic">
            <GeographicView />
          </TabsContent>

          <TabsContent value="trends">
            <TrendAnalysis />
          </TabsContent>

          <TabsContent value="resources">
            <ResourceAllocation />
          </TabsContent>

          <TabsContent value="reporting">
            <IncidentReporting />
          </TabsContent>

          <TabsContent value="predictive">
            <PredictiveAnalytics />
          </TabsContent>
        </Tabs>
      </main>
    </div>
  );
};

export default Index;
